details:
  namespace: student65-bookinfo-prd
  image: ghcr.io/miner3210/bookinfo-details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 1010
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.opsta.net
  path: "/student65/details(/|$)(.*)"
  serviceType: ClusterIP